policies:
  - type: commit
    spec:
      header:
        length: 89
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: false
      gpg: false
      spellcheck:
        locale: US
      conventional:
        types:
          - "build"
          - "chore"
          - "ci"
          - "docs"
          - "perf"
          - "refactor"
          - "revert"
          - "style"
          - "test"
          - "type"
        scopes:
          - "build"
          - "ci"
          - "cms"
          - "component"
          - "conform"
          - "deps"
          - "docs"
          - "format"
          - "page"
          - "sanity"
          - "style"
        descriptionLength: 72