policies:
  - type: commit
    spec:
      header:
        length: 89
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: false
      gpg: false
      spellcheck:
        locale: US
      conventional:
        types:
          - "build"
          - "chore"
          - "ci"
          - "docs"
          - "perf"
          - "refactor"
          - "style"
          - "test"
          - "type"
        descriptionLength: 72