name: Conform
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Conform Action
        uses: docker://autonomy/conform:v0.1.0-alpha.16


# on:
#   pull_request: [master]
#
# jobs:
#   test_pull_request:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Build Gatsby Site
#         uses: jzweifel/gatsby-cli-github-action@master
#         with:
#           gatsby-arg: build